### ISSUE TITLE
Enabling TSConfig strict mode result to TS2322

### ISSUE THREAD

**Issue by Rambou** [KrickRay/coerce-property#18]
Hi, by enabling the  `"strict": true,` in typescript compiler a.k.a. tsconfig.json it will result to the following Typescript error
```
TS2322: Type '(target: T, propertyKey: P) => void' is not assignable to type 'PropertyDecorator'.   Types of parameters 'target' and 'target' are incompatible.     Type 'Object' is not assignable to type 'T'.       'T' could be instantiated with an arbitrary type which could be unrelated to 'Object'
```
https://github.com/A77AY/coerce-property/blob/0d7a866550bebe87ed10dca07d282f39b37ad47d/src/coerce.ts#L13

**Comment by A77AY** [comment]
I will transfer to Angular CLI and update the package versions and typings...

(Temporarily I think you can enable the [skipLibCheck](https://www.typescriptlang.org/tsconfig#skipLibCheck))

**Comment by A77AY** [comment]
I completely updated under Angular CLI @15, if there is a similar problem, open a new issue

**Comment by Rambou** [comment]
Kudos
