### ISSUE TITLE
Type 'string' is not assignable to type 'boolean'

### ISSUE THREAD

**Issue by RadLikeWhoa** [KrickRay/coerce-property#23]
In my component I have declared the following input:

`@Input() @coerceBoolean public multiple: boolean = false;`

Trying to use it like `<component multiple></component>` gives me the following error:

`TS2322: Type 'string' is not assignable to type 'boolean'.`

I'm using the following tsconfig:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "target": "ES2022",
    "module": "es2020",
    "moduleResolution": "node",
    "downlevelIteration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "resolveJsonModule": true,
    "allowSyntheticDefaultImports": true,
    "skipLibCheck": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noEmitHelpers": true,
    "importHelpers": true,
    "pretty": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2020",
      "dom"
    ],
    "useDefineForClassFields": false
  },
  "angularCompilerOptions": {
    "strictInjectionParameters": true,
    "strictMetadataEmit": false,
    "fullTemplateTypeCheck": true,
    "strictTemplates": true
  },
  "atom": {
    "rewriteTsconfig": false
  }
}
```

Any ideas?

**Comment by A77AY** [comment]
~You need to specify a `string | boolean`:
`@Input() @coerceBoolean public multiple: string | boolean = false;`~
This is normal, because for this notation style, the `string` type from Angular will come, although `coerceBoolean` will actually always return a boolean

**Comment by A77AY** [comment]
You can specify the type more precisely: `boolean | ''`:
`@Input() @coerceBoolean public multiple: boolean | '' = false;`

**Comment by RadLikeWhoa** [comment]
The problem then is that the property cannot be passed directly to a child component that expects a boolean input.

```
@Component({
  template: `
    <ng-select [multiple]="multiple"></ng-select>
  `
})
export class TestComponent {
  @Input() @coerceBoolean public multiple: boolean | '' = false;
}
```

After removing the type definition works it works fine.

`@Input() @coerceBoolean public multiple = false;`

Edit: Actually, removing the type definition brings back the initial TS2322 error.

**Comment by A77AY** [comment]
In your case, you can write:

```ts
@Component({
  template: `
    <ng-select [multiple]="multiple || false"></ng-select>
  `
})
export class TestComponent {
  @Input() @coerceBoolean public multiple: boolean | '' = false;
}
```

**Comment by A77AY** [comment]
Probably this is better:
```ts
@Component({
  template: `
    <ng-select [multiple]="!!multiple"></ng-select>
  `
})
export class TestComponent {
  @Input() @coerceBoolean public multiple: boolean | '' = false;
}
```
