### ISSUE TITLE
Error during template compile of 'coerceBoolean'

### ISSUE THREAD

**Issue by Squidy06** [KrickRay/coerce-property#5]
Hi, after trying to use this tool following error throws:
```
Compiling TypeScript sources through ngc
ERROR: coerce-property/lib/coercions.ts(1,22): Error during template compile of 'coerceBoolean'
Only initialized variables and constants can be referenced in decorators because the value of this variable is needed by the template compiler.
```

Looks really useful for me, but is this still working in ng 9? :)

**Comment by A77AY** [comment]
@Squidy06, Ngcc shouldn't build the library. On the default project created from CLI on Angular 9 everything is ok.
You can send more details about your configuration or make minimal repo with error reproduction?
